[theme]
primaryColor = "#E24768"
backgroundColor = "#111111"
secondaryBackgroundColor = "#31333E"
codeBackgroundColor = "#212228"
textColor = "#FAFAFA"


font = "sans-serif"
baseFontSize = 20

headingFont = "sans-serif"
headingFontSizes = ["70", "54", "42", "35", "29", "24"]

codeFont = "monospace"